### ISSUE TITLE
Parsing erroneous literals containing double quotes

### ISSUE THREAD

**Issue by wouterbeek** [drobilla/serd#10]
The following is illegal in Turtle-based languages:

```ttl
<a:a> <a:a> """^^<b:b> .
<c:c> <c:c> """^^<b:b> .
```

But Serd 0.29.2 parses this, resulting in an output that is also illegal Turtle:

```sh
$ serdi test.ttl
<a:a> <a:a> "^^<b:b> .\n<c:c> <c:c> "^^<b:b> .
```

**Comment by drobilla** [comment]
Is it?  All the characters in the long literal are legal, and that long literal has datatype <b:b>.  That output is ntriples (by default), if you set it to turtle with `-o turtle` it will look similar to the input (but indented).

`rapper`, `rdfpipe` (rdflib), and `cwm` all have the same behaviour.

**Comment by wouterbeek** [comment]
Oops, the double quotes got to me there :)  closing...

**Comment by drobilla** [comment]
Took me a minute, too :)

Implementing these triple quotes is a bit annoying, but the official test suite covers the edge cases pretty well.
