### ISSUE TITLE
Why does lax mode not skip this line?

### ISSUE THREAD

**Issue by wouterbeek** [drobilla/serd#11]
I'm trying out line skipping in lax parsing mode, but I do not yet understand how it works.  For the following example the serdi command line tool gives the same result with and without lax mode:

```n-triples
<x:x> <x:x> <x:x> .
<y:y> <y:y> <y:z}> .
<z:z> <z:z> <z:z> .
```

```sh
$ serdi input.nt
<x:x> <x:x> <x:x> .
error: input.nt:2:127: invalid IRI character `{'
$ serdi -l input.nt
<x:x> <x:x> <x:x> .
error: input.nt:2:17: invalid IRI character `}'
```

Tested with serdi 0.29.2.

**Comment by drobilla** [comment]
Fixed in https://github.com/drobilla/serd/commit/87b4a8e5ce44d1d04908e3e981d775fb1a91ea85
