### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by alextone** [drobilla/serd#26]
alex@alextone:~/github/serd$  ./waf configure --prefix=/usr
Traceback (most recent call last):
  File "./waf", line 5, in <module>
    from waflib import Context, Scripting
ImportError: No module named waflib

**Comment by drobilla** [comment]
You need to update git submodules

**Comment by alextone** [comment]
Ok, thanks Dave.

**Comment by alextone** [comment]
Yep, that worked. 

Onwards and Upwards......
