### ISSUE TITLE
serd 0.30.8 build failure on mojave and catalina

### ISSUE THREAD

**Issue by chenrui333** [drobilla/serd#32]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>serd 0.30.8 test failure on mojave</summary>

```
==> serdi -
dyld: lazy symbol binding failed: Symbol not found: _aligned_alloc
  Referenced from: /usr/local/Cellar/serd/0.30.8/lib/libserd-0.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _aligned_alloc
  Referenced from: /usr/local/Cellar/serd/0.30.8/lib/libserd-0.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
```

</details>

<details>
<summary>serd 0.30.8 build failure on catalina</summary>

```
../src/serd_config.h:32:9: warning: 'SERD_VERSION' macro redefined [-Wmacro-redefined]
#define SERD_VERSION "0.30.7"
        ^
<command line>:2:9: note: previous definition is here
#define SERD_VERSION "0.30.8"
        ^
../src/system.c:59:10: error: implicit declaration of function 'aligned_alloc' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  return aligned_alloc(alignment, size);
         ^
../src/system.c:59:10: warning: incompatible integer to pointer conversion returning 'int' from a function with result type 'void *' [-Wint-conversion]
  return aligned_alloc(alignment, size);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings and 1 error generated.

In file included from ../src/serdi.c:19:
../src/serd_config.h:32:9: warning: 'SERD_VERSION' macro redefined [-Wmacro-redefined]
#define SERD_VERSION "0.30.7"
        ^
<command line>:2:9: note: previous definition is here
#define SERD_VERSION "0.30.8"
        ^
1 warning generated.
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/1678765724
relates to https://github.com/Homebrew/homebrew-core/pull/68697

**Comment by drobilla** [comment]
Actually an issue with building for older MacOS versions from newer ones, as I understand it (I am using Mojave and it worked fine).

Anyway, fixed (sort of) in c4c4ec51, thanks.

**Comment by chenrui333** [comment]
let me give that commit a try, thanks @drobilla!

**Comment by drobilla** [comment]
@chenrui333 You're welcome.  Let me know if it works, I botched a few things this time around and would like to make a point release soonish.

**Comment by chenrui333** [comment]
@drobilla looks like it still has some issue applying the patch, if you can do another release, that would be great. Thanks!

**Comment by drobilla** [comment]
The point is that I would like to know _before_ making a release so I don't have to do another one in 5 minutes ;)

**Comment by chenrui333** [comment]
I could do add your patch, and I did try [the commit ](https://github.com/Homebrew/formula-patches/commit/9b5c35d1c5f05bedc65f73a27ecc6f6123c0a8d4), unfortunately, that did not quite work. :(

**Comment by drobilla** [comment]
Can you be more specific?  Is there a CI run I can look at?  Sorry,  I don't really know how Homebrew packaging works, but if you can tell me how to reproduce what you're doing I can try myself (on Mojave)

**Comment by chenrui333** [comment]
@drobilla the new release actually works, resolved the build and get merged in [the same PR ](https://github.com/Homebrew/homebrew-core/pull/68697), thanks! 🎉

**Comment by drobilla** [comment]
Great.  Thanks for packaging!
