### ISSUE TITLE
Buggy occurrence of semicolon does not give an error

### ISSUE THREAD

**Issue by wouterbeek** [drobilla/serd#6]
The following buggy Turtle snippet is processed by Serd:

```ttl
<x:y> ; <x:y> <x:y> .
```

Serd does not parse a triple, but it also does not given an error.

Tested on Serd 0.29.1.

**Comment by drobilla** [comment]
Fixed in https://github.com/drobilla/serd/commit/91650728254f98e5949b28e3ad7bdac29047d2ae

I need to do some work on the test running glue to ensure that error messages are actually produced for failing cases one of these days...
